---
# tasks file for paultaiton.msteams
- name: microsoft rpm key
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Yum repo definitions 
  copy:
    dest: /etc/yum.repos.d
    owner: root
    group: root
    mode: 644
    src: "{{ item }}.repo"
  loop:
    - teams

- name: add extra packages
  dnf:
    name:
     - teams
    state: latest
